### ISSUE TITLE
I am very interested in your work, but A problem accured when install the setup.py.  Do you kown why?

### ISSUE THREAD

**Issue by NaCl96** [valeoai/LightConvPoint#1]
cc1plus: warning: command line option '-Wstrict-prototypes' is valid for C/ObjC but not for C++
./src/knn.cxx: In function 'at::Tensor knn(at::Tensor, at::Tensor, size_t)':
./src/knn.cxx:32:39: error: expected primary-expression before 'float'
  const float* pts_data = pts.data_ptr<float>();
                                       ^
./src/knn.cxx:38:40: error: expected primary-expression before 'float'
   const float* qrs_data = qrs.data_ptr<float>();
                                        ^
error: command 'gcc' failed with exit status 1

**Comment by aboulch** [comment]
Hello,
I cannot reproduce the error on my system: ubuntu 18.04 / Pytorch 1.4.0.
Did you find the origin of the bug ?
