### ISSUE TITLE
SemanticKITTI benchmark

### ISSUE THREAD

**Issue by jokester-zzz** [valeoai/LightConvPoint#2]
Hi, 
Thanks for your paper and code! Would you like to test on the SemanticKITTI benchmark, I'm very interested in the performance :)

Best,
Xuemeng

**Comment by aboulch** [comment]
Hello,
I do not know much about SemanticKITTI.
It not in the short term objectives but I will think about it.
In the mean time, if you code the thing, fill free create a pull request.
Best,
