### ISSUE TITLE
NPM3D Benchmark

### ISSUE THREAD

**Issue by code-by-lk** [valeoai/LightConvPoint#3]
Hello @valeoai and @aboulch,

Thank you for releasing the code behind your work. Are there any immediate plans to release an example for the NPM3D dataset?

Thanks in advance.

**Comment by aboulch** [comment]
Hello,
I plan to do that by the end of July / begning of August. I still have a lot of code refactoring to do.

**Comment by code-by-lk** [comment]
Hello @aboulch,

Thank you for your response. I look forward to seeing the examples later this summer and I want to thank you again for releasing everything open source.
